<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;

class AuthTest extends TestCase
{
    use DatabaseMigrations;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->startSession();
        $this->seed();
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function testSeesLoginLink()
    {
        $response = $this->get('/');

        $response->assertStatus(200);
        $response->assertSee('Login');
    }

    public function testRedirectsToLogin() {
        $response = $this->get('/home');

        $response->assertRedirect('/login');
    }

    public function testCreateUser() {
        $this->withoutMiddleware();

        $user = factory('App\User')->make();

        $userData = $user->toArray();

        $userData['password'] = 'secret';
        $userData['password_confirmation'] = 'secret';

        $response = $this->post('/register', $userData);

        $response->assertRedirect(route('home'));
    }

    /*public function testUnableToCreateInviteAnonymously() {

        //$user = factory('App\User')->create();

        $invite = factory('App\Invite')->make();

        $response = $this->post('/invites', $invite->toArray());
        //dd($response);
        $response->assertRedirect('/login');
    }*/
}
